int portugol_core_llvm_bibliotecas_portugol_core_llvm_bibliotecas_BibliotecaMouse_posicao_x();
int portugol_core_llvm_bibliotecas_portugol_core_llvm_bibliotecas_BibliotecaMouse_posicao_y();
int portugol_core_llvm_bibliotecas_portugol_core_llvm_bibliotecas_BibliotecaMouse_ler_botao();
int portugol_core_llvm_bibliotecas_portugol_core_llvm_bibliotecas_BibliotecaMouse_botao_pressionado(int botao);
int portugol_core_llvm_bibliotecas_portugol_core_llvm_bibliotecas_BibliotecaMouse_algum_botao_pressionado();